---
title: "posterior_analysis"
output: html_document
---

```{r}
rm(list=ls())
library(ggplot2)
library(dplyr)
library(coda)
```

# Import data
```{r}
posteriorSamples_gb <- read.csv("production_posterior_full_gb_10k_4p.csv")
posteriorSamples_inc <- read.csv("production_posterior_full_inc_10k_4p.csv")

posteriorPredictive_gb <- read.csv("production_posteriorPredictive_full_gb_10k_4p.csv")
posteriorPredictive_inc <- read.csv("production_posteriorPredictive_full_inc_10k_4p.csv")
```

Convert posterior samples to MCMC object
```{r}
posteriorSamples_gb_mcmc <- as.mcmc(posteriorSamples_gb)
posteriorSamples_inc_mcmc <- as.mcmc(posteriorSamples_inc)
```

# Posterior analysis

## Global Speaker
```{r}
plot(posteriorSamples_gb)
summary(posteriorSamples_gb_mcmc)
traceplot(posteriorSamples_gb_mcmc)
autocorr.plot(posteriorSamples_gb_mcmc)
effectiveSize(posteriorSamples_gb_mcmc)
```
## Incremental Speaker
```{r}
plot(posteriorSamples_inc)
summary(posteriorSamples_inc_mcmc)
traceplot(posteriorSamples_inc_mcmc)
autocorr.plot(posteriorSamples_inc_mcmc)
effectiveSize(posteriorSamples_inc_mcmc)
```
Look into the correlation between parameters
```{r}
cor_matrix <- cor(posteriorSamples_inc)
print(cor_matrix)
```


```{r}
x <- data$predictions[1]

# X is a vector of predictions stored in strings, we need to convert it to a list of numbers first
# first, get rid of [ at the beginning and ] at the end
convert_to_list <- function(x) {
  x <- gsub("\\[|\\]", "", x)
  # then split the string by comma
  x <- strsplit(x, ",")[[1]]
  # convert to numeric
  x <- as.numeric(x)
  return(x)
}

# apply to every row in data$predictions and store the results in a new dataframe called predictions
data$predictions %>% sapply(convert_to_list)
# with row now the values, and column the index

```

```{r}
# Extract unique statesArray in data and corresponding annotation_seq_flat
data %>% group_by(annotation) %>% ggplot(aes(x = annotation, fill = conditions)) +
  geom_bar()

data %>% group_by(annotation) %>% ggplot(aes(x = predictions, fill = conditions)) +
  geom_density()
```

```{r}
# Compute by condition mean
data %>%
  group_by(conditions) %>%
  summarise(mean_annotation = mean(annotation_seq_flat),
            mean_predictions = mean(mean_predictions)) -> by_condition_mean

ggplot(by_condition_mean, aes(x = mean_annotation, y = mean_predictions)) +
  geom_point() +
  geom_smooth(method = "lm") +
  theme_minimal()
```

